### ISSUE TITLE
Freescout error after activating module

### ISSUE THREAD

**Issue by MichaelGSP** [churcholution/freescout-churchtoolsauth#1]
hi there, 

after activating the module we can not access freescout anymore

<img width="1258" alt="image" src="https://github.com/user-attachments/assets/a16a264e-17b2-4de1-8fdc-37e31978877f">

The logs do not show anything related to it.

I downloaded the zip and pasted it to the module folder. After that I activated the module via the GUI.

**Comment by dev-swick** [comment]
The issue has been resolved. The name of the module folder has to be exactly `ChurchToolsAuth` (case-sensitive).
